language: cpp
compiler:
    - gcc
    - clang
before_script:
    - sudo apt-get update
    - sudo apt-get build-dep -qq xchat
    - sudo apt-get install -qq libnotify-dev libproxy-dev libpci-dev libcanberra-dev monodevelop gnome-common libboost-all-dev pkg-config
script: 
    - ./autogen.sh
    - ./configure --enable-textfe --with-theme-manager
    - make V=1 -j$(nproc)

matrix:
     fast_finish: true
