language: cpp
compiler:
    - gcc
before_install:
    - sudo add-apt-repository ppa:boost-latest/ppa  -y
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
before_script:
    - sudo apt-get update
    - sudo apt-get build-dep -qq xchat
    - sudo apt-get install -qq libnotify-dev libproxy-dev libpci-dev libcanberra-dev monodevelop gnome-common libboost1.55-all-dev pkg-config
script:
    - ./autogen.sh
    - ./configure --enable-textfe --with-theme-manager
    - make

matrix:
     fast_finish: true
